.PHONY: clean All

All:
	@echo "----------Building project:[ prog1 - Debug ]----------"
	@cd "prog1" && "$(MAKE)" -f  "prog1.mk"
clean:
	@echo "----------Cleaning project:[ prog1 - Debug ]----------"
	@cd "prog1" && "$(MAKE)" -f  "prog1.mk" clean
