.PHONY: clean All

All:
	@echo "----------Building project:[ prog2 - Debug ]----------"
	@cd "prog2" && "$(MAKE)" -f  "prog2.mk"
clean:
	@echo "----------Cleaning project:[ prog2 - Debug ]----------"
	@cd "prog2" && "$(MAKE)" -f  "prog2.mk" clean
